# Generated by Django 5.0.2 on 2024-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('headingX', models.IntegerField()),
                ('headingY', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateCode', models.CharField(max_length=3)),
                ('size', models.CharField(choices=[('L', 'Size Large'), ('M', 'Size Medium'), ('S', 'Size Small')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('size', models.CharField(choices=[('L', 'Size Large'), ('M', 'Size Medium'), ('S', 'Size Small')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('otherAttribute', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('airplanes', models.ManyToManyField(blank=True, to='airplane.airplane')),
                ('airports', models.ManyToManyField(blank=True, to='airplane.airport')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='gates',
            field=models.ManyToManyField(to='airplane.gate'),
        ),
        migrations.AddField(
            model_name='airport',
            name='runways',
            field=models.ManyToManyField(to='airplane.runway'),
        ),
    ]
