# Generated by Django 5.0.2 on 2024-10-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.PositiveIntegerField()),
                ('plane', models.CharField(max_length=4)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('landing_time', models.DateTimeField()),
                ('take_off_time', models.DateTimeField()),
            ],
        ),
    ]
