# Generated by Django 5.0.2 on 2024-10-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0002_takeoffrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateRunwayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(max_length=4)),
                ('gate', models.CharField(max_length=4)),
                ('runway', models.CharField(max_length=4)),
                ('arrive_at_time', models.DateTimeField()),
            ],
        ),
    ]
