# Generated by Django 5.0.2 on 2024-10-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0003_gaterunwayassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(max_length=4)),
                ('passenger_count', models.PositiveIntegerField()),
            ],
        ),
    ]
