# Generated by Django 5.0.2 on 2024-11-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0004_passengerassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='capacity',
            new_name='maxPassenger',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='headingX',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='headingY',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='location',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='gateCode',
        ),
        migrations.RemoveField(
            model_name='runway',
            name='code',
        ),
        migrations.AddField(
            model_name='airport',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gate',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gate',
            name='size',
            field=models.CharField(choices=[('LARGE', 'Size Large'), ('MEDIUM', 'Size Medium'), ('SMALL', 'Size Small')], max_length=6),
        ),
        migrations.AlterField(
            model_name='runway',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runway',
            name='size',
            field=models.CharField(choices=[('LARGE', 'Size Large'), ('MEDIUM', 'Size Medium'), ('SMALL', 'Size Small')], max_length=6),
        ),
    ]
