# Generated by Django 5.0.2 on 2024-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0005_rename_capacity_airplane_maxpassenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='size',
            field=models.CharField(choices=[('LARGE', 'Size Large'), ('MEDIUM', 'Size Medium'), ('SMALL', 'Size Small')], max_length=6),
        ),
    ]
