# Generated by Django 5.0.2 on 2024-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0006_alter_airplane_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='currentPassengerCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
