# Generated by Django 5.0.2 on 2024-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0007_airplane_currentpassengercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaterunwayassignment',
            name='plane',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerassignment',
            name='plane',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='takeoffrequest',
            name='plane',
            field=models.CharField(max_length=10),
        ),
    ]
