# Generated by Django 5.0.2 on 2024-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0008_alter_gaterunwayassignment_plane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaterunwayassignment',
            name='gate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gaterunwayassignment',
            name='runway',
            field=models.CharField(max_length=10),
        ),
    ]
